name: Deploy to Heroku
on:
  push:
    branches:
      - main  # or the name of your branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "online-game-discord-bot" #Must be unique in Heroku
        heroku_email: "yagi-shinichi@outlook.com"
